# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/3 --input_feat_path mydata/diabetes/feat --output_dir res/diabetes/3
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/6 --input_feat_path mydata/diabetes/feat --output_dir res/diabetes/6
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/9 --input_feat_path mydata/diabetes/feat --output_dir res/diabetes/9
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/12 --input_feat_path mydata/diabetes/feat --output_dir res/diabetes/12
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/15 --input_feat_path mydata/diabetes/feat --output_dir res/diabetes/15

# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/3 --input_feat_path mydata/tumor/feat --output_dir res/tumor/3
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/6 --input_feat_path mydata/tumor/feat --output_dir res/tumor/6
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/9 --input_feat_path mydata/tumor/feat --output_dir res/tumor/9
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/12 --input_feat_path mydata/tumor/feat --output_dir res/tumor/12
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/15 --input_feat_path mydata/tumor/feat --output_dir res/tumor/15

# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset hlt --pure_opt --K 11 --input_adj_path mydata/hlt/5 --input_feat_path mydata/hlt/feat --output_dir res/hlt/5
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset hlt --pure_opt --K 11 --input_adj_path mydata/hlt/10 --input_feat_path mydata/hlt/feat --output_dir res/hlt/10
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 5e-4 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset hlt --pure_opt --K 11 --input_adj_path mydata/hlt/15 --input_feat_path mydata/hlt/feat --output_dir res/hlt/15


# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/3 --input_feat_path mydata/tumor/feat --output_dir res_gap/tumor --objective cut
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/6 --input_feat_path mydata/tumor/feat --output_dir res_gap/tumor --objective cut
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/9 --input_feat_path mydata/tumor/feat --output_dir res_gap/tumor --objective cut
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/12 --input_feat_path mydata/tumor/feat --output_dir res_gap/tumor --objective cut
# python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset tumor --pure_opt --K 9 --input_adj_path mydata/tumor/15 --input_feat_path mydata/tumor/feat --output_dir res_gap/tumor --objective cut

python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/3 --input_feat_path mydata/diabetes/feat --output_dir res_gap/diabetes --objective cut
python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/6 --input_feat_path mydata/diabetes/feat --output_dir res_gap/diabetes --objective cut
python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/9 --input_feat_path mydata/diabetes/feat --output_dir res_gap/diabetes --objective cut
python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/12 --input_feat_path mydata/diabetes/feat --output_dir res_gap/diabetes --objective cut
python experiments_inductive2.py --hidden 50 --embed_dim 50 --weight_decay 0 --dropout 0.2 --train_epochs 100 --clustertemp 70 --num_cluster_iter 1 --lr 0.001 --dataset diabetes --pure_opt --K 6 --input_adj_path mydata/diabetes/15 --input_feat_path mydata/diabetes/feat --output_dir res_gap/diabetes --objective cut
